### ISSUE TITLE
Part #freenode

### ISSUE THREAD

**Issue by Svetlana-T** [NicholasRoge/ircbot#1]
#freenode is not for bot testing, please /part. please use #botters-test for testing. thanks :)

**Comment by NicholasRoge** [comment]
Yeah, should have asked permission first.  Apologies.  Was performing a large scale test to see how it coped with being connected to multiple channels.  In my defense, it should have been sent a kill signal after two minutes.  Only explanation I can come up with for why it didn't die is that it's predecessor to the terminator.  Should we begin looking for Sarah Connor?

All jokes aside, it won't happen again.
